# Generated by Django 5.0.6 on 2024-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_categories_categorie_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodct_image',
            field=models.ImageField(upload_to='media/product/images'),
        ),
    ]
