# Generated by Django 5.0.6 on 2024-06-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_product_prodct_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorie',
            new_name='category',
        ),
    ]
