# Generated by Django 5.0.6 on 2024-06-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_categorie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodct_image',
            new_name='product_image',
        ),
    ]
