# Generated by Django 5.0.6 on 2024-07-01 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_prodct_image_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
