# Generated by Django 5.0.6 on 2024-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_customuser_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
