# Generated by Django 5.0.6 on 2024-07-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_reviewcomment_date_created_bill_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.CharField(max_length=200),
        ),
    ]
