# Generated by Django 5.0.6 on 2024-07-05 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_bill_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='star',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
