# Generated by Django 5.0.6 on 2024-07-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_product_rating_review_star_reviewcomment_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='star',
        ),
    ]
