# Generated by Django 5.0.6 on 2024-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_rename_star_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_body',
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='review', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product/images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
