# Generated by Django 5.0.6 on 2024-07-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_rename_review_review_review_body_review_review_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomment',
            name='rating',
        ),
    ]
