# Generated by Django 5.0.6 on 2024-07-10 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvote_users',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvote_users',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_body',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
