# Generated by Django 5.0.6 on 2024-07-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_review_downvote_users_review_upvote_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='upvote_users',
            new_name='vote_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='downvote_users',
        ),
    ]
